# TCL File Generated by Component Editor 12.1sp1
# Thu Mar 14 11:20:06 JST 2013
# DO NOT MODIFY


# 
# Encoder_Reader "encoder_reader" v1.0
# null 2013.03.14.11:20:06
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module Encoder_Reader
# 
set_module_property NAME Encoder_Reader
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME encoder_reader
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL encoder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file encoder.vhd VHDL PATH encoder.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point myclock
# 
add_interface myclock clock end
set_interface_property myclock clockRate 0
set_interface_property myclock ENABLED true

add_interface_port myclock csi_myclock_clk clk Input 1


# 
# connection point myclock_reset
# 
add_interface myclock_reset reset end
set_interface_property myclock_reset associatedClock myclock
set_interface_property myclock_reset synchronousEdges DEASSERT
set_interface_property myclock_reset ENABLED true

add_interface_port myclock_reset csi_myclock_reset reset Input 1


# 
# connection point encoder
# 
add_interface encoder avalon end
set_interface_property encoder addressUnits WORDS
set_interface_property encoder associatedClock myclock
set_interface_property encoder associatedReset myclock_reset
set_interface_property encoder bitsPerSymbol 8
set_interface_property encoder burstOnBurstBoundariesOnly false
set_interface_property encoder burstcountUnits WORDS
set_interface_property encoder explicitAddressSpan 0
set_interface_property encoder holdTime 0
set_interface_property encoder linewrapBursts false
set_interface_property encoder maximumPendingReadTransactions 0
set_interface_property encoder readLatency 0
set_interface_property encoder readWaitTime 1
set_interface_property encoder setupTime 0
set_interface_property encoder timingUnits Cycles
set_interface_property encoder writeWaitTime 0
set_interface_property encoder ENABLED true

add_interface_port encoder avs_encoder_read_n read_n Input 1
add_interface_port encoder avs_encoder_chipselect chipselect Input 1
add_interface_port encoder avs_encoder_address address Input 2
add_interface_port encoder avs_encoder_readdata readdata Output 32
add_interface_port encoder avs_encoder_writedata writedata Input 32
set_interface_assignment encoder embeddedsw.configuration.isFlash 0
set_interface_assignment encoder embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment encoder embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment encoder embeddedsw.configuration.isPrintableDevice 0


# 
# connection point encoder_input
# 
add_interface encoder_input conduit end
set_interface_property encoder_input associatedClock myclock
set_interface_property encoder_input associatedReset myclock_reset
set_interface_property encoder_input ENABLED true

add_interface_port encoder_input coe_encoder_input_export export Input 1

