# TCL File Generated by Component Editor 12.1sp1
# Sat Mar 09 14:16:34 JST 2013
# DO NOT MODIFY


# 
# PWM "PWM" v1.0
# null 2013.03.09.14:16:34
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module PWM
# 
set_module_property NAME PWM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME PWM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pwm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file PWM.vhd VHDL PATH PWM.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point myclock
# 
add_interface myclock clock end
set_interface_property myclock clockRate 0
set_interface_property myclock ENABLED true

add_interface_port myclock csi_myclock_clk clk Input 1


# 
# connection point myclock_reset
# 
add_interface myclock_reset reset end
set_interface_property myclock_reset associatedClock myclock
set_interface_property myclock_reset synchronousEdges DEASSERT
set_interface_property myclock_reset ENABLED true

add_interface_port myclock_reset csi_myclock_reset reset Input 1


# 
# connection point pwm
# 
add_interface pwm avalon end
set_interface_property pwm addressUnits WORDS
set_interface_property pwm associatedClock myclock
set_interface_property pwm associatedReset myclock_reset
set_interface_property pwm bitsPerSymbol 8
set_interface_property pwm burstOnBurstBoundariesOnly false
set_interface_property pwm burstcountUnits WORDS
set_interface_property pwm explicitAddressSpan 0
set_interface_property pwm holdTime 0
set_interface_property pwm linewrapBursts false
set_interface_property pwm maximumPendingReadTransactions 0
set_interface_property pwm readLatency 0
set_interface_property pwm readWaitTime 1
set_interface_property pwm setupTime 0
set_interface_property pwm timingUnits Cycles
set_interface_property pwm writeWaitTime 0
set_interface_property pwm ENABLED true

add_interface_port pwm avs_pwm_chipselect chipselect Input 1
add_interface_port pwm avs_pwm_address address Input 2
add_interface_port pwm avs_pwm_readdata readdata Output 16
add_interface_port pwm avs_pwm_writedata writedata Input 16
add_interface_port pwm avs_pwm_write_n write_n Input 1
set_interface_assignment pwm embeddedsw.configuration.isFlash 0
set_interface_assignment pwm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment pwm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment pwm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pwm_output
# 
add_interface pwm_output conduit end
set_interface_property pwm_output associatedClock myclock
set_interface_property pwm_output associatedReset myclock_reset
set_interface_property pwm_output ENABLED true

add_interface_port pwm_output coe_pwm_output_export export Output 1

